-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  google_event_id text NOT NULL,
  google_calendar_id text NOT NULL,
  title text,
  description text,
  location text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  is_all_day boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'confirmed'::text,
  visibility text NOT NULL DEFAULT 'default'::text,
  attendee_count integer NOT NULL DEFAULT 0,
  is_organizer boolean NOT NULL DEFAULT false,
  response_status text,
  is_recurring boolean NOT NULL DEFAULT false,
  recurring_event_id text,
  raw_event jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.calendar_sync_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  sync_type text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['initiated'::text, 'fetching'::text, 'compressing'::text, 'completed'::text, 'failed'::text])),
  events_fetched integer NOT NULL DEFAULT 0,
  events_added integer NOT NULL DEFAULT 0,
  events_updated integer NOT NULL DEFAULT 0,
  events_deleted integer NOT NULL DEFAULT 0,
  google_api_calls integer NOT NULL DEFAULT 0,
  scaledown_called boolean NOT NULL DEFAULT false,
  scaledown_duration_ms integer,
  scaledown_error text,
  total_duration_ms integer,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  error_message text,
  error_stack text,
  sync_triggered_by text,
  CONSTRAINT calendar_sync_history_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_sync_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.compressed_calendars (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  source_event_count integer NOT NULL,
  compressed_size_bytes integer,
  compression_ratio numeric,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  availability_patterns jsonb NOT NULL,
  busy_probability_map jsonb NOT NULL,
  meeting_density_scores jsonb NOT NULL,
  preferred_meeting_times jsonb,
  typical_work_hours jsonb,
  average_meeting_duration_minutes integer,
  most_common_meeting_types jsonb,
  scaledown_model_version text,
  scaledown_request_id text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT compressed_calendars_pkey PRIMARY KEY (id),
  CONSTRAINT compressed_calendars_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.enforcement_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id text NOT NULL,
  rule_type text NOT NULL CHECK (rule_type = ANY (ARRAY['buffer_time'::text, 'travel_time'::text, 'cancellation_risk'::text, 'time_savings'::text, 'recurring_optimization'::text])),
  rule_action text NOT NULL CHECK (rule_action = ANY (ARRAY['pass'::text, 'block'::text, 'warn'::text, 'optimize'::text])),
  rule_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  candidate_slot jsonb,
  enforced_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enforcement_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meeting_candidates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  slot_start timestamp with time zone NOT NULL,
  slot_end timestamp with time zone NOT NULL,
  slot_timezone text NOT NULL DEFAULT 'UTC'::text,
  final_score numeric NOT NULL,
  rank integer NOT NULL CHECK (rank > 0),
  availability_score numeric NOT NULL,
  preference_score numeric NOT NULL,
  optimization_score numeric NOT NULL,
  conflict_proximity_score numeric NOT NULL,
  fragmentation_score numeric NOT NULL,
  all_participants_available boolean NOT NULL,
  conflict_participant_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  reasoning text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meeting_candidates_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_candidates_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id)
);
CREATE TABLE public.meetings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id text NOT NULL UNIQUE,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  participant_count integer NOT NULL,
  required_participant_count integer NOT NULL,
  optional_participant_count integer NOT NULL,
  duration_minutes integer NOT NULL,
  earliest_date timestamp with time zone NOT NULL,
  latest_date timestamp with time zone NOT NULL,
  buffer_minutes integer NOT NULL DEFAULT 15,
  success boolean NOT NULL,
  total_candidates_evaluated integer NOT NULL,
  candidates_returned integer NOT NULL,
  processing_time_ms numeric NOT NULL,
  negotiation_rounds integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'cancelled'::text])),
  selected_candidate_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  google_event_id text,
  google_calendar_id text DEFAULT 'primary'::text,
  writeback_status text DEFAULT 'pending'::text CHECK (writeback_status = ANY (ARRAY['pending'::text, 'created'::text, 'failed'::text, 'retrying'::text])),
  writeback_error text,
  writeback_attempted_at timestamp with time zone,
  writeback_succeeded_at timestamp with time zone,
  writeback_retry_count integer DEFAULT 0,
  google_event_link text,
  enforcement_status text DEFAULT 'pending'::text CHECK (enforcement_status = ANY (ARRAY['pending'::text, 'passed'::text, 'blocked'::text, 'warning'::text])),
  enforcement_rules_applied jsonb DEFAULT '[]'::jsonb,
  enforcement_blocks jsonb DEFAULT '[]'::jsonb,
  cancellation_risk text DEFAULT 'unknown'::text CHECK (cancellation_risk = ANY (ARRAY['unknown'::text, 'low'::text, 'medium'::text, 'high'::text])),
  cancellation_risk_factors jsonb DEFAULT '{}'::jsonb,
  time_savings_minutes integer DEFAULT 0,
  time_savings_metrics jsonb DEFAULT '{}'::jsonb,
  buffer_violations integer DEFAULT 0,
  travel_violations integer DEFAULT 0,
  CONSTRAINT meetings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.oauth_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'google'::text,
  access_token text NOT NULL,
  refresh_token text,
  token_type text NOT NULL DEFAULT 'Bearer'::text,
  expires_at timestamp with time zone NOT NULL,
  scopes ARRAY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_refreshed_at timestamp with time zone,
  CONSTRAINT oauth_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.participant_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  user_id text NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  is_required boolean NOT NULL,
  total_busy_slots integer NOT NULL DEFAULT 0,
  weekly_meeting_count integer NOT NULL DEFAULT 0,
  peak_meeting_hours jsonb NOT NULL DEFAULT '[]'::jsonb,
  preferred_days jsonb NOT NULL DEFAULT '[]'::jsonb,
  preferred_hours_start integer,
  preferred_hours_end integer,
  morning_person_score numeric,
  avoids_back_to_back boolean,
  buffer_minutes integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT participant_availability_pkey PRIMARY KEY (id),
  CONSTRAINT participant_availability_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id)
);
CREATE TABLE public.recurring_meeting_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_pattern_id text NOT NULL,
  participant_emails ARRAY NOT NULL,
  current_slot jsonb NOT NULL,
  avg_score numeric NOT NULL,
  score_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  suggested_slot jsonb,
  optimization_reason text,
  analyzed_at timestamp with time zone NOT NULL DEFAULT now(),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'applied'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recurring_meeting_analysis_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scheduling_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL UNIQUE,
  estimated_time_saved_minutes numeric NOT NULL,
  coordination_overhead_reduction_pct numeric NOT NULL,
  top_candidate_confidence numeric NOT NULL,
  avg_candidate_score numeric NOT NULL,
  candidates_evaluated integer NOT NULL,
  total_conflicts integer NOT NULL DEFAULT 0,
  conflict_rate numeric NOT NULL DEFAULT 0.00,
  most_constrained_participant_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  candidates_without_conflicts integer NOT NULL DEFAULT 0,
  total_participants integer NOT NULL,
  morning_people_ratio numeric,
  avg_preferred_start_hour numeric,
  avg_preferred_end_hour numeric,
  buffer_sensitive_ratio numeric,
  total_slots_evaluated integer NOT NULL,
  required_participants integer NOT NULL,
  optional_participants integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scheduling_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT scheduling_analytics_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id)
);
CREATE TABLE public.score_breakdowns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  candidate_id uuid NOT NULL,
  availability_factor numeric NOT NULL,
  preference_factor numeric NOT NULL,
  conflict_proximity_factor numeric NOT NULL,
  fragmentation_factor numeric NOT NULL,
  optimization_factor numeric NOT NULL,
  availability_weight integer NOT NULL DEFAULT 35,
  preference_weight integer NOT NULL DEFAULT 25,
  conflict_proximity_weight integer NOT NULL DEFAULT 20,
  fragmentation_weight integer NOT NULL DEFAULT 15,
  optimization_weight integer NOT NULL DEFAULT 5,
  availability_details jsonb,
  conflict_proximity_details jsonb,
  fragmentation_details jsonb,
  optimization_details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT score_breakdowns_pkey PRIMARY KEY (id),
  CONSTRAINT score_breakdowns_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.meeting_candidates(id)
);
CREATE TABLE public.user_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  google_user_id text UNIQUE,
  display_name text,
  profile_picture_url text,
  is_active boolean NOT NULL DEFAULT true,
  calendar_sync_enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  CONSTRAINT user_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  availability jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_availability_pkey PRIMARY KEY (id),
  CONSTRAINT user_availability_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_accounts(id)
);